//The problem states that : Each new term in the Fibonacci sequence is generated by
// adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
//find the sum of the even-valued terms.

var x = 1;                  //Initiating x
var y = 2;                  //Initiating y
var z = 0;                  //Initiating z
var sum = 0;                //Initiating sum

while (x < 4000000)         //A while loop to keep the number under 4 million as stated in the problem
{

  if(x % 2 === 0)           //checking whether the number is even
   {
     sum += x;              // if number is even, adds to the value of sum
   }
//generating fibonacci seq

 z = x + y;                 
  x = y;                    
  y = z;

}
 
 console.log(sum);          //displaying sum
